import test from 'node:test';
import assert from 'node:assert/strict';
import {createQuotationRepository} from '../../src/quotations/repository.js';
import {newForm,freshTemplate,quoteLabel,pdfName,documentFor} from '../../src/quotations/model.js';
import {memoryClient} from './memoryClient.mjs';
const user={id:'owner',name:'Agent',phone:'9876543210'};
async function setup(){const client=memoryClient();const repo=createQuotationRepository(client);const form={...newForm(user),customer_name:'Ramesh Kumar Patel',customer_phone:'9876543211',capacity_kw:3.48,solar_panel_qty:6,panel_wattage:580,solar_panel_make:'Waaree',inverter_option:'Option 1',inverter_brand:'Solaryan',options:['a','b','c'].map(brandName=>({brandName,baseValue:100000,discount:100,subsidy:1000}))};const row=await repo.save('quote',null,form,freshTemplate(),user);return{client,repo,form,row};}

test('an issued quotation is locked against edits',async()=>{const{repo,row,form}=await setup();const issued=await repo.generated(row,user);await assert.rejects(repo.save('quote',issued,{...form,customer_name:'Changed'},freshTemplate(),user),/locked/);});
test('revise creates R1 and marks the original as replaced',async()=>{const{repo,row}=await setup();const issued=await repo.generated(row,user);const r1=await repo.revise(issued,user);assert.equal(quoteLabel(r1),`Quote-${issued.quotation_no}-R1`);assert.equal(r1.status,'draft');assert.equal(r1.quotation_data.form.customer_name,'Ramesh Kumar Patel');const original=await repo.get(issued.id);assert.equal(original.quotation_data.superseded_by.id,r1.id);await assert.rejects(repo.revise(original,user),/already revised/);const r1Issued=await repo.generated(r1,user);const r2=await repo.revise(r1Issued,user);assert.equal(quoteLabel(r2),`Quote-${issued.quotation_no}-R2`);assert.equal(documentFor(r2).page1.quotationNo,`Quote-${issued.quotation_no}-R2`);});
test('PDF is named after the customer full name',async()=>{const{repo,row}=await setup();assert.equal(pdfName(row),'Ramesh Kumar Patel.pdf');const r1=await repo.revise(await repo.generated(row,user),user);assert.equal(pdfName(r1),'Ramesh Kumar Patel (R1).pdf');});
test('converted stays converted while the lead exists, and is cleared when the lead is deleted',async()=>{const{repo,row,client}=await setup();await repo.insertConversionLead(row,{customer_name:'Lead'},user);let fresh=await repo.get(row.id);assert.equal((await repo.verifyConversion(fresh)).converted_lead_id,row.id);client.state.tables.admin[0].deleted_at='2026-10-04';fresh=await repo.verifyConversion(await repo.get(row.id));assert.equal(fresh.converted_lead_id,null);assert.notEqual(fresh.status,'converted');const again=await repo.insertConversionLead(fresh,{customer_name:'Lead again'},user);assert.notEqual(again.data.id,row.id);assert.equal((await repo.get(row.id)).converted_lead_id,again.data.id);});
test('a converted quotation cannot be revised or edited',async()=>{const{repo,row,form}=await setup();await repo.insertConversionLead(row,{customer_name:'Lead'},user);const converted=await repo.get(row.id);await assert.rejects(repo.revise(converted,user),/converted/);await assert.rejects(repo.save('quote',converted,{...form,customer_name:'X'},freshTemplate(),user),/locked/);});
