// src/constants.js  —  Watersun Electrical Solutions Pvt Ltd
// Generated by SolarFlow Client Form · 6 August 2026 at 15:50
// CRN prefix: CRN-2026-

import {
    Users, ClipboardList, IndianRupee, Package, PauseCircle, Truck,
    Wrench, Camera, Send, Gauge, Zap, Activity, ClipboardCheck, CheckCircle2,
    Clock, AlertTriangle, Banknote, Tag, ShoppingBag
} from 'lucide-react';

export const PRIMARY_STAGES = [
    { id: 'LEADS', label: 'Leads', icon: Users },
    { id: 'REGISTRATION', label: 'Registration', icon: ClipboardList },
    { id: 'LOAN', label: 'Loan', icon: IndianRupee },
    { id: 'CASH', label: 'Cash', icon: Banknote },
    { id: 'HOLD PROCUREMENT', label: 'Hold Procurement', icon: PauseCircle },
    { id: 'MATERIAL ORDER', label: 'Material Order', icon: ShoppingBag },
    { id: 'MATERIAL INTEGRATION', label: 'Material Integration', icon: Package },
    { id: 'MATERIAL DELIVERY', label: 'Material Delivery', icon: Truck },
    { id: 'INSTALLATION STATUS', label: 'Installation Status', icon: Wrench },
    { id: 'GEO TAG PHOTO', label: 'Geo Tag Photo', icon: Camera },
    { id: 'DISCOM SUBMISSION', label: 'Discom Submission', icon: Send },
    { id: 'METER INSTALLATION', label: 'Meter Installation', icon: Gauge },
    { id: 'DISCOM INSPECTION', label: 'Discom Inspection', icon: ClipboardCheck },
    { id: 'SUBSIDY STATUS', label: 'Subsidy Status', icon: Tag },
    { id: 'FINAL REVIEW', label: 'Final Review', icon: ClipboardCheck },
    { id: 'COMPLETED', label: 'Completed', icon: CheckCircle2 },
];

export const SUBSIDY_TAGS = [
    { id: 'Redeemed', label: 'Redeemed', icon: Banknote },
    { id: 'Returned', label: 'Returned', icon: Clock },
    { id: 'Approved', label: 'Approved', icon: CheckCircle2 },
    { id: 'Received', label: 'Received', icon: CheckCircle2 },
];

export const SUBSIDY_TAG_COLORS = {
    'Approved': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Returned': { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-400' },
    'Rejected': { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'Redeemed': { bg: 'bg-blue-50',    text: 'text-blue-700',    border: 'border-blue-200',    dot: 'bg-blue-400' },
    'Received': { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-400' },
};

export const LOAN_TAGS = [
    { id: 'Processed', label: 'Processed', icon: Activity },
    { id: 'Sanctioned', label: 'Sanctioned', icon: CheckCircle2 },
    { id: 'Returned', label: 'Returned', icon: Clock },
    { id: 'Rejected', label: 'Rejected', icon: AlertTriangle },
    { id: '1st Payment', label: '1st Payment', icon: Banknote },
    { id: '2nd Payment', label: '2nd Payment', icon: Banknote },
];

export const LOAN_TAG_COLORS = {
    'Processed':  { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-400' },
    'Sanctioned': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Rejected':   { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'Returned':   { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-400' },
    '1st Payment': { bg: 'bg-blue-50',   text: 'text-blue-700',   border: 'border-blue-200',   dot: 'bg-blue-400' },
    '2nd Payment': { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200', dot: 'bg-indigo-400' },
};

// Supabase metadata table categories (one per managed dropdown)
export const META_CATEGORIES = ['payment_type', 'module_brand', 'payment_method_modes', 'subsidy_approval_status', 'registration_by'];

export const APP_ROLES = [
    { id: 'admin', label: 'Admin', user_type: 'admin', role: 'Admin' },
    { id: 'office', label: 'Office', user_type: 'sales', role: 'Office' },
    { id: 'channel_partner_office', label: 'Channel Partner Office', user_type: 'channel_partner_office', role: 'Channel Partner Office' },
    { id: 'channel_partner', label: 'Channel Partners', user_type: 'agent', role: 'Channel Partners' },
    { id: 'vendor', label: 'Vendors', user_type: 'vendor', role: 'Vendors' },
    { id: 'stamp', label: 'Stamp Guy', user_type: 'stamp', role: 'Stamp' },
];


// ============================================================
// ROOF BOM TEMPLATE (Exact Order)
// ============================================================

export const ROOF_BOM_TEMPLATE = [
    { sr_no: 1,  product_name: 'Solar Panel',             quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 2,  product_name: 'Inverter',                quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 3,  product_name: 'ACDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 4,  product_name: 'DCDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 5,  product_name: 'Dc Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 6,  product_name: 'Earthing Cable',          quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 7,  product_name: '16sq MM LA cabel',        quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 8,  product_name: 'Ac Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 9,  product_name: 'Isolation box+MCB',       quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 10, product_name: 'Shadel',                  quantity: '50',    uom: 'No.', quantity_editable: false },
    { sr_no: 11, product_name: 'Elbow',                   quantity: '35',    uom: 'No.', quantity_editable: false },
    { sr_no: 12, product_name: 'Tea',                     quantity: '7',     uom: 'No.', quantity_editable: false },
    { sr_no: 13, product_name: 'Wedge Anchor Fast',       quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 14, product_name: '8 aani 4 inch',           quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 15, product_name: '6 aani 6 inch',           quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 16, product_name: 'jasti khila',             quantity: '8',     uom: 'No.', quantity_editable: false },
    { sr_no: 17, product_name: 'm c 4 conectar',           quantity: '2',     uom: 'No.', quantity_editable: false },
    { sr_no: 18, product_name: 'Screw/ Tape',             quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 19, product_name: '16 sq MM Round LUG',      quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 20, product_name: '4 sq MM Round LUG',       quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 21, product_name: '4 Sqmm Pin Type Lug',     quantity: '10',    uom: 'No.', quantity_editable: false },
    { sr_no: 22, product_name: 'Red/Black Sleeve',        quantity: '5+2',   uom: 'No.', quantity_editable: false },
    { sr_no: 23, product_name: '5 aani 2inch',            quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 24, product_name: 'Mid Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 25, product_name: 'End Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 26, product_name: 'GI Clamp',                quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 27, product_name: 'u bolt+patti',            quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 28, product_name: 'Chaki+Wisher',            quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 29, product_name: 'Sapot pati',              quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 30, product_name: 'rubar cap',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 31, product_name: 'cabale ties',             quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 32, product_name: 'Cable Tie ( Nani )',      quantity: '36',    uom: 'No.', quantity_editable: false },
    { sr_no: 33, product_name: 'Earth Pit Doll',          quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 34, product_name: '40*40 Pipe Perlin',       quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 35, product_name: '60*40 Pipe rafter',       quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 36, product_name: '60*40 front leg',         quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 37, product_name: '60*40 Rear leg',          quantity: '',      uom: 'Feet', quantity_editable: true },
    { sr_no: 38, product_name: 'LA  insuletar',           quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 39, product_name: 'cabale tre',              quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 40, product_name: 'Earthing Kit + LA',       quantity: '3+1',   uom: 'No.', quantity_editable: false },
    { sr_no: 41, product_name: 'chemical',                quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 42, product_name: 'Conduite Pipe',           quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 43, product_name: 'Cement',                  quantity: '',      uom: 'Bag', quantity_editable: true },
    { sr_no: 44, product_name: 'Reti',                    quantity: '',      uom: 'Bag (50 kg)', quantity_editable: true },
    { sr_no: 45, product_name: 'Kapachi',                 quantity: '',      uom: 'Bag (50 kg)', quantity_editable: true },
];


// ============================================================
// SHED BOM TEMPLATE (Exact Order)
// ============================================================

export const SHED_BOM_TEMPLATE = [
    { sr_no: 1,  product_name: 'Solar Panel',             quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 2,  product_name: 'Inverter',                quantity: '',      uom: 'Nos', quantity_editable: true },
    { sr_no: 3,  product_name: 'ACDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 4,  product_name: 'DCDB',                    quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 5,  product_name: 'Dc Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 6,  product_name: 'Earthing Cable',          quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 7,  product_name: '16sq MM LA Cable',        quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 8,  product_name: 'Ac Cable',                quantity: '',      uom: 'MTR', quantity_editable: true },
    { sr_no: 9,  product_name: 'Isolation box+MCB',       quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 10, product_name: 'Shadel',                  quantity: '50',    uom: 'No.', quantity_editable: false },
    { sr_no: 11, product_name: 'Elbow',                   quantity: '35',    uom: 'No.', quantity_editable: false },
    { sr_no: 12, product_name: 'Tea',                     quantity: '7',     uom: 'No.', quantity_editable: false },
    { sr_no: 13, product_name: 'Spring + HEX Bolt',       quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 14, product_name: 'L And Key',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 15, product_name: '80*40 J bolt mota',       quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 16, product_name: 'Damar roll',              quantity: '2',     uom: 'MTR', quantity_editable: false },
    { sr_no: 17, product_name: 'jasti khila',             quantity: '8',     uom: 'No.', quantity_editable: false },
    { sr_no: 18, product_name: 'm c 4 conectar',           quantity: '2',     uom: 'No.', quantity_editable: false },
    { sr_no: 19, product_name: '16 sq MM Round LUG',      quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 20, product_name: '4 sq MM Round LUG',       quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 21, product_name: '4 Sqmm Pin Type Lug',     quantity: '10',    uom: 'No.', quantity_editable: false },
    { sr_no: 22, product_name: 'Red/Black Sleeve',        quantity: '5+2',   uom: 'No.', quantity_editable: false },
    { sr_no: 23, product_name: '5 aani 2inch',            quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 24, product_name: 'Mid Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 25, product_name: 'End Clamp',               quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 26, product_name: 'LA  insuletar',           quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 27, product_name: 'cabale ties',             quantity: '15',    uom: 'No.', quantity_editable: false },
    { sr_no: 28, product_name: 'Earthing ડોલ / ઢાંકણા', quantity: '3',     uom: 'No.', quantity_editable: false },
    { sr_no: 29, product_name: 'C Chanel',                quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 30, product_name: 'Z mota',                  quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 31, product_name: 'Z nana',                  quantity: '',      uom: 'No.', quantity_editable: true },
    { sr_no: 32, product_name: 'cabale tre',              quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 33, product_name: 'Earthing Kit + LA',       quantity: '3+1',   uom: 'No.', quantity_editable: false },
    { sr_no: 34, product_name: 'chemical',                quantity: '1',     uom: 'No.', quantity_editable: false },
    { sr_no: 35, product_name: 'Condute Pipe',            quantity: '15',    uom: 'No.', quantity_editable: false },
];

export const COMMON_BOM_ITEMS = ROOF_BOM_TEMPLATE.filter(r => 
    SHED_BOM_TEMPLATE.some(s => s.product_name.toLowerCase().trim() === r.product_name.toLowerCase().trim())
);