// src/constants.js  —  Watersun Electrical Solutions Pvt Ltd
// Generated by SolarFlow Client Form · 6 August 2026 at 15:50
// CRN prefix: CRN-2026-

import {
    Users, ClipboardList, IndianRupee, Package, PauseCircle, Truck,
    Wrench, Camera, Send, Gauge, Zap, Activity, ClipboardCheck, CheckCircle2,
    Clock, AlertTriangle, Banknote, Tag,
} from 'lucide-react';

export const PRIMARY_STAGES = [
    { id: 'LEADS', label: 'Leads', icon: Users },
    { id: 'REGISTRATION', label: 'Registration', icon: ClipboardList },
    { id: 'LOAN', label: 'Loan', icon: IndianRupee },
    { id: 'MATERIAL PROCUREMENT', label: 'Material Procurement', icon: Package },
    { id: 'HOLD PROCUREMENT', label: 'Hold Procurement', icon: PauseCircle },
    { id: 'MATERIAL DELIVERY', label: 'Material Delivery', icon: Truck },
    { id: 'INSTALLATION STATUS', label: 'Installation Status', icon: Wrench },
    { id: 'GEO TAG PHOTO', label: 'Geo Tag Photo', icon: Camera },
    { id: 'DISCOM SUBMISSION', label: 'Discom Submission', icon: Send },
    { id: 'METER INSTALLATION', label: 'Meter Installation', icon: Gauge },
    { id: 'DISCOM INSPECTION', label: 'Discom Inspection', icon: ClipboardCheck },
    { id: 'SUBSIDY STATUS', label: 'Subsidy Status', icon: Tag },
    { id: 'FINAL REVIEW', label: 'Final Review', icon: ClipboardCheck },
    { id: 'COMPLETED', label: 'Completed', icon: CheckCircle2 },
];

export const SUBSIDY_TAGS = [
    { id: 'Redeemed', label: 'Redeemed', icon: Banknote },
    { id: 'Returned', label: 'Returned', icon: Clock },
    { id: 'Approved', label: 'Approved', icon: CheckCircle2 },
    { id: 'Received', label: 'Received', icon: CheckCircle2 },
];

export const SUBSIDY_TAG_COLORS = {
    'Approved': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Returned': { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-400' },
    'Rejected': { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'Redeemed': { bg: 'bg-blue-50',    text: 'text-blue-700',    border: 'border-blue-200',    dot: 'bg-blue-400' },
    'Received': { bg: 'bg-indigo-50',  text: 'text-indigo-700',  border: 'border-indigo-200',  dot: 'bg-indigo-400' },
};

export const LOAN_TAGS = [
    { id: 'Sanctioned', label: 'Sanctioned', icon: CheckCircle2 },
    { id: 'Returned', label: 'Returned', icon: Clock },
    { id: 'Rejected', label: 'Rejected', icon: AlertTriangle },
    { id: '1st Payment', label: '1st Payment', icon: Banknote },
    { id: '2nd Payment', label: '2nd Payment', icon: Banknote },
];

export const LOAN_TAG_COLORS = {
    'Sanctioned': { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-400' },
    'Rejected':   { bg: 'bg-rose-50',    text: 'text-rose-700',    border: 'border-rose-200',    dot: 'bg-rose-400' },
    'Returned':   { bg: 'bg-amber-50',   text: 'text-amber-700',   border: 'border-amber-200',   dot: 'bg-amber-400' },
    '1st Payment': { bg: 'bg-blue-50',   text: 'text-blue-700',   border: 'border-blue-200',   dot: 'bg-blue-400' },
    '2nd Payment': { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200', dot: 'bg-indigo-400' },
};

// Supabase metadata table categories (one per managed dropdown)
export const META_CATEGORIES = ['payment_type', 'module_brand', 'payment_method_modes', 'subsidy_approval_status', 'branch_name', 'registration_by'];

export const APP_ROLES = [
    { id: 'admin', label: 'Admin', user_type: 'admin', role: 'Admin' },
    { id: 'office', label: 'Office', user_type: 'sales', role: 'Office' },
    { id: 'channel_partner', label: 'Channel Partners', user_type: 'agent', role: 'Channel Partners' },
];
